#include "NvM_Types.h"
#include "Rte.h"

Task(OS_StartUp_Task)
{
    EcuM_StartUp_Two();
}

Task(OS_10ms_Cyclic_Task)
{
    /*This is the Task body context*/

    NvM_MainFunction();
    Fee_MainFunction();
    Ea_MainFunction();
    Eep_MainFunction();
    Fls_MainFunction();

    BswM_MainFunction();

    Autosar_CDD_MainFunction();
}

/*
 *Client Server Interface
 *Rte_Call_<Component_Name>_<RPort_Name>_<Operation_Name>
 */

Std_ReturnType Rte_Call_AUTOSAR_CDD_NvM_Engine_Block_WriteBlock(const void *data)
{
    return NvM_WriteBlock(7, data); /*The value 499 will be automatically generated by the RTE*/
}

Std_ReturnType Rte_Call_AUTOSAR_CDD_NvM_Kilometer_Block_WriteBlock(data)
{
    return NvM_WriteBlock(5, data); /*The value 499 will be automatically generated by the RTE*/
}

Std_ReturnType Rte_Call_AUTOSAR_CDD_NvM_Speed_Block_WriteBlock(data)
{
    return NvM_WriteBlock(6, data); /*The value 499 will be automatically generated by the RTE*/
}

Std_ReturnType Rte_Call_AUTOSAR_CDD_NvM_Engine_Block_ReadBlock(data)
{
    return NvM_ReadBlock(7, data);
}

Std_ReturnType Rte_Call_AUTOSAR_CDD_NvM_Kilometer_Block_ReadBlock(data)
{
    return NvM_ReadBlock(5, data);
}

Std_ReturnType Rte_Call_AUTOSAR_CDD_NvM_Speed_Block_ReadBlock(data)
{
    return NvM_ReadBlock(6, data);
}

Std_ReturnType Rte_Read_ReadKilometerPort_Kilometer(uint8 *data)
{
    (void)Com_ReceiveSignal(6, data);

    return 0;
}

Std_ReturnType Rte_Read_ReadEnginePort_Engine(uint8 *data)
{
    (void)Com_ReceiveSignal(5, data);

    return 0;
}

Std_ReturnType Rte_Read_ReadSpeedPort_Speed(uint8 *data)
{
    (void)Com_ReceiveSignal(7, data);

    return 0;
}
